base_url = "https://alastairrushworth.github.io/"
compile_sass = true
title = "alastair rushworth"
description = "A blog about data science and other things"

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[extra]
author = "alastair"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
after_dark_title = "My blog"
