base_url = "https://alastairrushworth.github.io/"
title = "alastair rushworth"
description = "a blog about data science and other things"
theme = "even"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
favicon = "/icon/favicon.png"
author = "Alastair Rushworth"
even_title = "alastair rushworth"
mathjax = true
katex_enable = true
katex_auto_render = true
stylesheets = ["custom.css"]

even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/tags", name = "Tags"},
]

