base_url = "https://alastairrushworth.github.io/"
compile_sass = true
title = "alastair rushworth"
description = "A blog about data science and other things"

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[extra]
author = "alastair"
after_dark_menu = [
    {url = "$BASE_URL", name = "home"},
    {url = "$BASE_URL/about", name = "about"},
    {url = "$BASE_URL/recipes", name = "recipes"},
]
after_dark_title = "My blog"

[search]
index_format = "elasticlunr_javascript"

[markdown]
highlight_code = true
highlight_theme = "custom_gruvbox"
extra_syntaxes_and_themes = ["syntaxes", "highlight_themes"]