base_url = "https://alastairrushworth.github.io/"
compile_sass = true
title = "alastair rushworth"
description = "A blog about data science and other things"

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[extra]
author = "alastair"
after_dark_menu = [
    {url = "$BASE_URL", name = "home"},
    {url = "$BASE_URL/about", name = "about"},
    {url = "$BASE_URL/recipes", name = "recipes"},
    {url = "$BASE_URL/categories", name = "categories"},
    {url = "$BASE_URL/tags", name = "tags"},
]
after_dark_title = "My blog"

[search]
index_format = "elasticlunr_javascript"
