name: Zola

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.17.2
      env:
        # This uses the standard GitHub token provided by GitHub Actions
        GITHUB_TOKEN: ${{ secrets.GHPAT}}
        # Make sure the base_url matches your GitHub Pages URL
        PAGES_BRANCH: gh-pages
        BUILD_DIR: .